version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      # npm run build -> For react application
  post_build:
    commands:
      - echo Post build complete 
      
# The code below may be used to store artifacts to s3
#artifacts:
#  files:
#   - '**/*'
#  base-directory: build
